services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb_server
    restart: unless-stopped
    ports:
      - "${COUCH_PORT:-5984}:5984"
    environment:
      COUCHDB_USER: ${COUCH_USER}
      COUCHDB_PASSWORD: ${COUCH_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data

  postgres:
    image: postgres:15
    container_name: postgres_server
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-ai-agents}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  couchdb_data:
    driver: local
  postgres_data:
    driver: local
